website/__init__.py
from flask import Flask
from website.views import views

def create_app():
    app = Flask(__name__)
    app.secret_key = 'safasafsafasa' 
    app.register_blueprint(views) 
    return app

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session, jsonify
import sqlite3, time
import random

views = Blueprint('views', __name__)

# Lista svih stranica za zadatke

TASK_PAGES_EASY = [
    "easy3.html",
    "easy2.html",
    "easy1.html",
    
]



TASK_PAGES_MEDIUM = [
     "medium2.html",
     "medium1.html",
     "medium3.html",
    
  
]

TASK_PAGES_HARD = [
    "hard1.html",
    "hard2.html",
    "hard3.html",
    

]

random.shuffle(TASK_PAGES_EASY)
random.shuffle(TASK_PAGES_MEDIUM)
random.shuffle(TASK_PAGES_HARD)


TASK_PAGES_GRUPA1 = TASK_PAGES_EASY + TASK_PAGES_MEDIUM + TASK_PAGES_HARD
TASK_PAGES_GRUPA2 = TASK_PAGES_EASY + TASK_PAGES_HARD + TASK_PAGES_MEDIUM
TASK_PAGES_GRUPA3 = TASK_PAGES_MEDIUM + TASK_PAGES_EASY + TASK_PAGES_HARD
TASK_PAGES_GRUPA4 = TASK_PAGES_MEDIUM + TASK_PAGES_HARD + TASK_PAGES_EASY
TASK_PAGES_GRUPA5 = TASK_PAGES_HARD + TASK_PAGES_EASY + TASK_PAGES_MEDIUM
TASK_PAGES_GRUPA6 = TASK_PAGES_HARD + TASK_PAGES_MEDIUM + TASK_PAGES_EASY


  # Slučajno rasporedi stranice

@views.route('/track')
def track():
    if 'username' not in session or 'selected_device' not in session:
        return redirect(url_for('views.home'))  # Preusmjeri na home ako uređaj nije odabran
    
    # Početak zadataka
    session['current_task_index'] = 0
    username = session['username']
    device = session['selected_device']
    return render_template(TASK_PAGES_GRUPA2[0], username=username, device=device)


@views.route('/', methods=['GET', 'POST'])
def login():
    if 'username' in session:
        return redirect(url_for('views.home'))
    
    if request.method == 'POST':
        username = request.form['username']
        session['username'] = username
        session['selected_device'] = None  # Resetiraj odabir uređaja pri loginu
        return redirect(url_for('views.home'))
    
    return render_template('login.html')

@views.route('/home', methods=['GET', 'POST'])
def home():
    if 'username' not in session:
        return redirect(url_for('views.login')) 
    
    username = session['username']

    if request.method == 'POST':
        selected_device = request.form.get('device')
        if selected_device:
            session['selected_device'] = selected_device
            return redirect(url_for('views.track'))
    
    return render_template('home.html', username=username)

@views.route('/logout')
def logout():
    session.pop('username', None)
    session.pop('selected_device', None)
    session.pop('current_task_index', None)
    return redirect(url_for('views.login'))

@views.route('/task-completed', methods=['POST'])
def task_completed():
    data = request.get_json()

    elapsed_time = data.get('elapsedTime')
    error_count = data.get('errorCount')
    username = session.get('username')
    trackId = data.get('trackId')
    device = session.get('selected_device')
    
    conn = sqlite3.connect('database.db')
    c = conn.cursor()

    c.execute('''INSERT INTO task_results (time, errors, username, trackid, device)
                 VALUES (?, ?, ?, ?, ?)''', (elapsed_time, error_count, username, trackId, device))
    
    conn.commit()
    conn.close()

    time.sleep(3)

    # Postavi indeks za sljedeću stranicu
    current_index = session.get('current_task_index', 0)
    if current_index < len(TASK_PAGES_GRUPA2) - 1:
        session['current_task_index'] = current_index + 1
        next_page = TASK_PAGES_GRUPA2[current_index + 1]
    else:
        return jsonify({"message": "Sve stranice su završene.", "finished": True}), 200

    return jsonify({"message": "Podaci su uspješno pohranjeni.", "next_page": next_page}), 200

@views.route('/next-task')
def next_task():
    current_index = session.get('current_task_index', 0)
    if current_index >= len(TASK_PAGES_GRUPA2):
        return redirect(url_for('views.home'))  # Vraćamo se na početak nakon svih zadataka

    username = session['username']
    device = session['selected_device']
    return render_template(TASK_PAGES_GRUPA2[current_index], username=username, device=device)

website/templates/Untitled.html
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -75.675 1151.3399 556.351" width="1151.34px" height="556.351px">
  <path style="fill: rgb(216, 216, 216); stroke: rgb(0, 0, 0);" d="M 15.265 480.676 C 29.773 480.676 50.28 477.459 62.033 471.582 C 66.216 469.49 72.698 473.258 75.674 470.283 C 76.464 469.492 82.227 470.283 83.469 470.283 C 89.863 470.283 97.819 470.912 103.605 468.983 C 112.5 466.019 126.501 469.633 135.434 469.633 C 161.2 469.633 186.965 469.633 212.731 469.633 C 226.614 469.633 240.195 468.334 253.654 468.334 C 260.989 468.334 272.101 469.503 278.337 466.385 C 282.963 464.072 290.621 468.392 293.927 465.086 C 294.717 464.296 300.479 465.086 301.721 465.086 C 309.949 465.086 318.177 465.086 326.405 465.086 C 360.431 465.086 394.109 463.787 427.736 463.787 C 469.092 463.787 510.447 463.787 551.803 463.787 C 566.923 463.787 584.901 465.096 598.571 460.539 C 601.759 459.477 607.272 461.385 610.263 459.89 C 622.005 454.019 640.594 457.391 652.485 451.445 C 662.242 446.567 678.539 449.136 688.211 444.3 C 695.601 440.605 704.338 441.739 712.244 439.104 C 727.455 434.033 744.909 431.031 761.611 425.463 C 769.851 422.716 779.524 423.002 786.294 419.617 C 808.398 408.565 834.969 404.699 857.096 393.634 C 879.097 382.634 901.736 373.913 923.352 363.105 C 927.897 360.832 938.068 359.432 941.539 355.96 C 949.146 348.353 964.282 339.067 974.667 333.875 C 988.624 326.897 995.293 306.753 1005.85 296.2 C 1011.26 290.783 1014.69 282.806 1019.49 278.012 C 1021.79 275.707 1021.51 268.196 1024.03 265.671 C 1033.13 256.575 1035.26 242.107 1044.17 233.193 C 1046.99 230.375 1046.2 224.021 1048.72 221.501 C 1058.27 211.952 1065.98 193.459 1071.45 182.527 C 1080.42 164.594 1092.99 136.954 1105.88 124.066 C 1125.78 104.165 1150.7 87.154 1150.7 52.614" id="object-2" transform="matrix(1, 0, 0, 1, 0, 1.4210854715202004e-14)"/>
  <path style="fill: rgb(216, 216, 216); stroke: rgb(0, 0, 0); transform-origin: 15.914px 420.77px;" d="M 0 480.026 L 0 353.004" id="object-0"/>
  <path style="fill: rgb(216, 216, 216); stroke: rgb(0, 0, 0);" d="M 15.915 352.387 C 30.423 352.387 50.93 349.17 62.683 343.293 C 66.866 341.201 73.348 344.969 76.324 341.994 C 77.114 341.203 82.877 341.994 84.119 341.994 C 90.513 341.994 98.469 342.623 104.255 340.694 C 113.15 337.73 127.151 341.344 136.084 341.344 C 161.85 341.344 187.615 341.344 213.381 341.344 C 227.264 341.344 240.845 340.045 254.304 340.045 C 261.639 340.045 272.751 341.214 278.987 338.096 C 283.613 335.783 291.271 340.103 294.577 336.797 C 295.367 336.007 301.129 336.797 302.371 336.797 C 310.599 336.797 318.827 336.797 327.055 336.797 C 361.081 336.797 394.759 335.498 428.386 335.498 C 469.742 335.498 511.097 335.498 552.453 335.498 C 567.573 335.498 585.551 336.807 599.221 332.25 C 602.409 331.188 607.922 333.096 610.913 331.601 C 622.655 325.73 641.244 329.102 653.135 323.156 C 662.892 318.278 679.189 320.847 688.861 316.011 C 696.251 312.316 704.988 313.45 712.894 310.815 C 728.105 305.744 745.559 302.742 762.261 297.174 C 770.501 294.427 780.174 294.713 786.944 291.328 C 809.048 280.276 835.619 276.41 857.746 265.345 C 879.747 254.345 902.386 245.624 924.002 234.816 C 928.547 232.543 938.718 231.143 942.189 227.671 C 949.796 220.064 964.932 210.778 975.317 205.586 C 989.274 198.608 995.943 178.464 1006.49 167.911 C 1011.91 162.494 1015.34 154.517 1020.13 149.723 C 1022.44 147.418 1022.16 139.907 1024.68 137.382 C 1033.77 128.286 1035.9 113.818 1044.82 104.904 C 1047.64 102.086 1046.84 95.732 1049.36 93.212 C 1058.91 83.663 1066.63 65.17 1072.1 54.238 C 1081.07 36.305 1093.64 8.665 1106.52 -4.223 C 1126.43 -24.124 1151.34 -41.135 1151.34 -75.675" id="object-3" transform="matrix(1, 0, 0, 1, 0, 1.4210854715202004e-14)"/>
  <path style="fill: rgb(216, 216, 216); stroke: rgb(0, 0, 0);" d="M 1151.338 -75.802 L 1151.338 52.308" id="object-1" transform="matrix(1, 0, 0, 1, 0, 1.4210854715202004e-14)"/>

</svg>

website/templates/base.html
<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HCI Tunnel</title>

    <!-- CDN za Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- CDN za Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    <!-- Dodatni stilovi mogu se dodati ovdje -->
    {% block extra_css %}
    {% endblock %}
</head>
<body>

    <!-- Navigacija -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">HCI Tunnel experiment</a>
            <ul class="navbar-nav ms-auto">
                {% if session.get('username') %}
                    <!-- Prikazivanje korisničkog imena i logout opcije ako je korisnik prijavljen -->
                    <li class="nav-item">
                        <span class="nav-link">Prijavljeni ste kao: {{ session.get('username') }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <!-- Prikazivanje linka za Login ako korisnik nije prijavljen -->
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.login') }}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Glavni sadržaj stranice -->
    <div class="container mt-4" style="margin: 0;">
        {% block content %}
        <h1>Dobrodošli na našu stranicu!</h1>
        <p>Ovdje možete postaviti dinamičke podatke i koristiti Font Awesome ikone kao npr. <i class="fas fa-home"></i> za ikonu.</p>
        {% endblock %}
    </div>

    <!-- Skripte -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    {% block extra_js %}
    {% endblock %}
</body>
</html>

website/templates/easy1.html
{% extends "base.html" %}

{% block content %}
<h2>Staza za prolazak mišem</h2>
<p>Pomaknite kursor unutar staze i dođite do cilja</p>

<div id="hiddenUsername" style="display:none;">{{ username }}</div>
<div id="hiddenTrackID" style="display:none;">Easy1</div>

<!-- Wrapping container -->
<div class="center-container">
  <!-- SVG for the maze with the width of the tunnel set to 100px -->
  <svg width="1900" height="600" style="border: 1px solid black;">
    <!-- Start Line -->
    <path id="startLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 50 450 L 50 550"></path>

    <!-- Stop Line -->
    <path id="stopLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 1800 50 L 1800 150"></path>

    <!-- Upper Line (Straight, Tunnel width 100px) -->
    <path id="upperLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 450 H 400 V 100 H 750 V 100 H 1000 V 450 H 1500 V 50 H 1600 V 50 H 1800"></path>

    <!-- Lower Line (Straight, Tunnel width 100px) -->
    <path id="lowerLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 550 H 500 V 200 H 850 V 200 H 900 V 550 H 1600 V 150 H 1600 V 150 H 1800"></path>
  </svg>

  <!-- Results container -->
  <div id="result-container" class="container text-center mt-4" >
    <div id="timeDisplay" class="h4" style="width: 1900px;"></div>
    <div id="errorCountDisplay" class="h5 mt-2" style="width: 1900px;"></div>
    <!-- Success message -->
    <div id="successMessage" class="alert alert-success mt-3 d-none" role="alert" style="width: 1900px;">
      Uspješno završen zadatak, {{ username }}!
    </div>
  </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/mouse_tracking.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/time_and_error_tracking.js') }}"></script>
{% endblock %}

website/templates/easy3.html
{% extends "base.html" %}

{% block content %}
<h2>Staza za prolazak mišem</h2>
<p>Pomaknite kursor unutar staze i dođite do cilja</p>

<div id="hiddenUsername" style="display:none;">{{ username }}</div>
<div id="hiddenTrackID" style="display:none;">Easy3</div>

<!-- Wrapping container -->
<div class="center-container">
  <!-- SVG for the maze with the width of the tunnel set to 100px -->
  <svg width="1900" height="600" style="border: 1px solid black;">
    <!-- Start Line -->
    <path id="startLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 50 400 L 50 500"></path>

    <!-- Stop Line -->
    <path id="stopLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 1750 400 L 1750 500"></path>

    <!-- Upper Line (Straight, Tunnel width 100px) -->
    <path id="upperLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 400 H 300 V 300 H 750 V 100 H 1100 V 400 H 1750"></path>

    <!-- Lower Line (Straight, Tunnel width 100px) -->
    <path id="lowerLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 500 H 400 V 400 H 850 V 200 H 1000 V 500 H 1750"></path>
  </svg>

  <!-- Results container -->
  <div id="result-container" class="container text-center mt-4" >
    <div id="timeDisplay" class="h4" style="width: 1900px;"></div>
    <div id="errorCountDisplay" class="h5 mt-2" style="width: 1900px;"></div>
    <!-- Success message -->
    <div id="successMessage" class="alert alert-success mt-3 d-none" role="alert" style="width: 1900px;">
      Uspješno završen zadatak, {{ username }}!
    </div>
  </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/mouse_tracking.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/time_and_error_tracking.js') }}"></script>
{% endblock %}

website/templates/hard1.html
{% extends "base.html" %}

{% block content %}
<h2>Staza za prolazak mišem</h2>
<p>Pomaknite kursor unutar staze i dođite do cilja</p>

<div id="hiddenUsername" style="display:none;">{{ username }}</div>
<div id="hiddenTrackID" style="display:none;">Hard1</div>

<!-- Wrapping container -->
<div class="center-container">
  <!-- SVG for the maze -->
  <svg width="1900" height="600" style="border: 1px solid black;">
    <!-- Start Line -->
    <path id="startLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 50 300 L 50 350"></path>

    <!-- Stop Line -->
    <path id="stopLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 1500 400 L 1500 450"></path>

    <!-- Upper Line -->
    <path id="upperLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 300 H 400 V 200 H 800 V 150 H 1300 V 400 H 1300 V 400 H 1500"></path>

    <!-- Lower Line -->
    <path id="lowerLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 350 H 450 V 250 H 850 V 200 H 1250 V 450 H 1250 V 450 H 1500"></path>
  </svg>

  <!-- Results container -->
  <div id="result-container" class="container text-center mt-4" >
    <div id="timeDisplay" class="h4" style="width: 1900px;"></div>
    <div id="errorCountDisplay" class="h5 mt-2" style="width: 1900px;"></div>
    <!-- Success message -->
    <div id="successMessage" class="alert alert-success mt-3 d-none" role="alert" style="width: 1900px;">
      Uspješno završen zadatak, {{ username }}!
    </div>
  </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/mouse_tracking.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/time_and_error_tracking.js') }}"></script>
{% endblock %}

website/templates/hard2.html
{% extends "base.html" %}

{% block content %}
<h2>Staza za prolazak mišem</h2>
<p>Pomaknite kursor unutar staze i dođite do cilja</p>

<div id="hiddenUsername" style="display:none;">{{ username }}</div>
<div id="hiddenTrackID" style="display:none;">Hard2</div>

<!-- Wrapping container -->
<div class="center-container">
  <!-- SVG for the maze -->
  <svg width="1900" height="600" style="border: 1px solid black;">
    <!-- Start Line -->
    <path id="startLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 50 300 L 50 350"></path>

    <!-- Stop Line -->
    <path id="stopLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 1700 300 L 1700 350"></path>

    <!-- New Upper Line (Straight) -->
    <path id="upperLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 350 H 400 V 100 H 800 V 150 H 1200 V 250 H 1500 V 350 H 1500 V 350 H 1700"></path>

    <!-- New Lower Line (Straight) -->
    <path id="lowerLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 300 H 350 V 50 H 850 V 100 H 1250 V 200 H 1550 V 300 H 1550 V 300 H 1700"></path>
  </svg>

  <!-- Results container -->
  <div id="result-container" class="container text-center mt-4" >
    <div id="timeDisplay" class="h4" style="width: 1900px;"></div>
    <div id="errorCountDisplay" class="h5 mt-2" style="width: 1900px;"></div>
    <!-- Success message -->
    <div id="successMessage" class="alert alert-success mt-3 d-none" role="alert" style="width: 1900px;">
      Uspješno završen zadatak, {{ username }}!
    </div>
  </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/mouse_tracking.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/time_and_error_tracking.js') }}"></script>
{% endblock %}

website/templates/hard3.html
{% extends "base.html" %}

{% block content %}
<h2>Staza za prolazak mišem</h2>
<p>Pomaknite kursor unutar staze i dođite do cilja</p>

<div id="hiddenUsername" style="display:none;">{{ username }}</div>
<div id="hiddenTrackID" style="display:none;">Hard3</div>

<!-- Wrapping container -->
<div class="center-container">
  <!-- SVG for the maze -->
  <svg width="1900" height="600" style="border: 1px solid black;">
    <!-- Start Line -->
    <path id="startLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 50 450 L 50 500"></path>

    <!-- Stop Line -->
    <path id="stopLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 1800 50 L 1800 100"></path>

    <!-- New Upper Line (Straight, Lower Position) -->
    <path id="upperLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 450 H 400 V 300 H 750 V 300 H 800 V 150 H 1300 V 450 H 1500 V 50 H 1550 V 50 H 1800"></path>

    <!-- New Lower Line (Straight, Lower Position) -->
    <path id="lowerLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 500 H 450 V 350 H 800 V 350 H 850 V 200 H 1250 V 500 H 1550 V 100 H 1550 V 100 H 1800"></path>
  </svg>

  <!-- Results container -->
  <div id="result-container" class="container text-center mt-4" >
    <div id="timeDisplay" class="h4" style="width: 1900px;"></div>
    <div id="errorCountDisplay" class="h5 mt-2" style="width: 1900px;"></div>
    <!-- Success message -->
    <div id="successMessage" class="alert alert-success mt-3 d-none" role="alert" style="width: 1900px;">
      Uspješno završen zadatak, {{ username }}!
    </div>
  </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/mouse_tracking.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/time_and_error_tracking.js') }}"></script>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 400px; margin-left: 60%;">
    <h2 class="text-center">Dobrodošli, {{ username }}</h2>
    <p class="text-center">Molimo odaberite uređaj za kontroliranje pokazivača:</p>

    <form id="deviceForm" method="POST" action="{{ url_for('views.home') }}">
        <select id="deviceSelection" name="device" class="form-select" required>
            <option value="" disabled selected>--Odaberite uređaj--</option>
            <option value="mouse">Miš</option>
            <option value="trackpad">Trackpad</option>
        </select>

        <div class="text-center mt-4">
            <button id="startTrackButton" type="button" class="btn btn-primary">Započni eksperiment</button>
        </div>
    </form>
</div>

<script>
    // Validacija odabira uređaja prije slanja forme
    document.getElementById("startTrackButton").addEventListener("click", function () {
        const selectedDevice = document.getElementById("deviceSelection").value;
        
        if (!selectedDevice) {
            alert("Molimo odaberite uređaj!"); 
            return;
        }

        document.getElementById("deviceForm").submit();
    });
</script>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="d-flex justify-content-center align-items-center vh-100">
    <div class="border p-4 rounded shadow" style="max-width: 400px; width: 100%; box-sizing: border-box; margin-left: 55%;">
      <h2 class="text-center mb-4">Login</h2>
      <form action="/" method="POST">
        <div class="mb-3">
          <label for="username" class="form-label">Ime:</label>
          <input type="text" id="username" name="username" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary w-100">Prijava</button>
      </form>
    </div>
  </div>
{% endblock %}

website/templates/medium1.html
{% extends "base.html" %}

{% block content %}
<h2>Staza za prolazak mišem</h2>
<p>Pomaknite kursor unutar staze i dođite do cilja</p>

<div id="hiddenUsername" style="display:none;">{{ username }}</div>
<div id="hiddenTrackID" style="display:none;">Medium1</div>

<!-- Wrapping container -->
<div class="center-container">
  <!-- SVG for the maze -->
  <svg width="1900" height="600" style="border: 1px solid black;">
    <!-- Start Line -->
    <path id="startLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 50 350 L 50 425"></path>

    <!-- Stop Line -->
    <path id="stopLine" style="fill: none; stroke: rgb(0, 0, 0);" d="M 1850 200 L 1850 275"></path>

    <!-- Upper Line -->
    <path id="upperLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 350 H 300 V 200 H 600 V 75 H 1075 V 275 H 1200 V 125 H 1550 V 325 H 1700 V 200 H 1850"></path>

    <!-- Lower Line -->
    <path id="lowerLine" style="fill: none; stroke: rgb(0, 0, 0);" 
          d="M 50 425 H 375 V 275 H 675 V 150 H 1000 V 350 H 1275 V 200 H 1475 V 400 H 1775 V 275 H 1850"></path>
  </svg>

  <!-- Results container -->
  <div id="result-container" class="container text-center mt-4" >
    <div id="timeDisplay" class="h4" style="width: 1900px;"></div>
    <div id="errorCountDisplay" class="h5 mt-2" style="width: 1900px;"></div>
    <!-- Success message -->
    <div id="successMessage" class="alert alert-success mt-3 d-none" role="alert" style="width: 1900px;">
      Uspješno završen zadatak, {{ username }}!
    </div>
  </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/mouse_tracking.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/time_and_error_tracking.js') }}"></script>
{% endblock %}